export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS';
export const SEARCH_COUNTRIES_SUCCESS = 'SEARCH_COUNTRIES_SUCCESS';
export const ORDER_COUNTRIES_SUCCESS = 'ORDER_COUNTRIES_SUCCESS';
export const FILTER_BY_CONTINENT_SUCCESS = 'FILTER_BY_CONTINENT_SUCCESS';
export const GET_CONTINENTS = 'GET_CONTINENTS';
export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const GET_COUNTRIES_BY_ACT ='GET_COUNTRIES_BY_ACT';